### PR TITLE
Allow user/repo format

### PR DESCRIPTION
**Pull request by alhassanv**
This PR allows validation to also work on user/repo format such as `digitalocean/hacktoberfest`.
I have tested this PR and it works perfectly!

This PR implements #46

### CODE REVIEW

**Comment by alhassanv** [comment]
@lukeocodes Please review this.

**Comment by alhassanv** [comment]
Tested new changes, works flawlessly!

**Review by lukeocodes — APPROVED** [review]
Yeh, this is a lot neater, a lot smaller. Streamlineeeeddd!! 🎉

Great job

**Comment by lukeocodes** [comment]
@all-contributors add @alhassanv for code

**Pull request merged**
